CREATE TABLE [dbo].[LEC_LCAR] (
    [TELCO]       NVARCHAR (4)  NULL,
    [CAR]         NVARCHAR (4)  NOT NULL,
    [SER]         NVARCHAR (6)  NOT NULL,
    [SERMOD]      INT           NOT NULL,
    [JURIS]       TINYINT       NOT NULL,
    [ORIG]        NVARCHAR (5)  NOT NULL,
    [DEST]        NVARCHAR (4)  NULL,
    [ZONE]        TINYINT       NOT NULL,
    [LATA]        NVARCHAR (3)  NULL,
    [ITEMCODE]    NVARCHAR (8)  NOT NULL,
    [ITEMBITS]    TINYINT       NOT NULL,
    [ITEMTERM]    SMALLINT      NOT NULL,
    [ITEMREV]     INT           NOT NULL,
    [ITEMMOD]     REAL          NOT NULL,
    [ITEMU]       NVARCHAR (6)  NULL,
    [ITEMNUM]     SMALLINT      NOT NULL,
    [ITEMNUMTYPE] NVARCHAR (1)  NULL,
    [P0]          FLOAT (53)    NULL,
    [P0U]         NVARCHAR (6)  NULL,
    [P0DIS]       TINYINT       NULL,
    [P1]          FLOAT (53)    NULL,
    [P1U]         NVARCHAR (6)  NULL,
    [P1DIS]       TINYINT       NULL,
    [EFFDATE]     SMALLDATETIME NULL,
    [EXPDATE]     SMALLDATETIME NULL,
    [TELCOID]     NVARCHAR (4)  NULL,
    [CIP]         REAL          NULL,
    [IP]          SMALLINT      NULL,
    [CPMAP]       REAL          NULL
);

