CREATE TABLE [dbo].[tblAgentConfig] (
    [AgentID]                   VARCHAR (7)     NOT NULL,
    [state]                     CHAR (2)        NOT NULL,
    [RateID]                    VARCHAR (2)     NULL,
    [PIFInterStPerMinCharge]    DECIMAL (4, 2)  NULL,
    [PIFInterStPerCallCharge]   DECIMAL (10, 4) NULL,
    [PIFInterStPerLimitCharge]  TINYINT         NULL,
    [PIFInterLaPerMinCharge]    DECIMAL (10, 4) NULL,
    [PIFInterLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [PIFInterLaPerLimitCharge]  TINYINT         NULL,
    [PIFIntraLaPerMinCharge]    DECIMAL (10, 4) NULL,
    [PIFIntraLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [PIFIntraLaPerLimitCharge]  TINYINT         NULL,
    [PIFIntlPerCallcharge]      DECIMAL (10, 4) NULL,
    [PIFIntlPerMinCharge]       DECIMAL (10, 4) NULL,
    [PIFIntlLimitCharge]        TINYINT         NULL,
    [NSFInterStPerCallCharge]   DECIMAL (10, 4) NULL,
    [NSFInterLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [NSFIntraLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [NSFIntlPerCallCharge]      DECIMAL (10, 4) NULL,
    [PSCInterStPerCallCharge]   DECIMAL (10, 4) NULL,
    [PSCInterLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [PSCIntraLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [PSCIntlPerCallCharge]      DECIMAL (10, 4) NULL,
    [NIFInterStPerCallCharge]   DECIMAL (10, 4) NULL,
    [NIFInterLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [NIFIntraLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [NIFIntlPerCallCharge]      DECIMAL (10, 4) NULL,
    [BDFInterStPerCallCharge]   DECIMAL (10, 4) NULL,
    [BDFInterLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [BDFIntraLaPerCallCharge]   DECIMAL (10, 4) NULL,
    [BDFIntlPerCallCharge]      DECIMAL (10, 4) NULL,
    [A4250InterStPerCallCharge] DECIMAL (10, 4) NULL,
    [A4250InterLaPerCallCharge] DECIMAL (10, 4) NULL,
    [A4250IntraLaPerCallCharge] DECIMAL (10, 4) NULL,
    [A4250IntlPerCallCharge]    DECIMAL (10, 4) NULL,
    [LibraryCode]               CHAR (2)        NOT NULL,
    [RatePlanOption]            TINYINT         NOT NULL,
    [IntlRate]                  VARCHAR (4)     NULL,
    [Fee1InterStPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee1InterLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee1IntraLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee1IntlPerCallCharge]     DECIMAL (10, 4) NULL,
    [Fee2InterStPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee2InterLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee2IntraLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee2IntlPerCallCharge]     DECIMAL (10, 4) NULL,
    [Fee3InterStPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee3InterLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee3IntraLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee3IntlPerCallCharge]     DECIMAL (10, 4) NULL,
    [Fee4InterStPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee4InterLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee4IntraLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee4IntlPerCallCharge]     DECIMAL (10, 4) NULL,
    [Fee5InterStPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee5InterLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee5IntraLaPerCallCharge]  DECIMAL (10, 4) NULL,
    [Fee5IntlPerCallCharge]     DECIMAL (10, 4) NULL,
    [Fee6InterStPerCallCharge]  DECIMAL (4, 2)  NULL,
    [Fee6InterLaPerCallCharge]  DECIMAL (4, 2)  NULL,
    [Fee6IntraLaPerCallCharge]  DECIMAL (4, 2)  NULL,
    [Fee6IntlPerCallCharg]      DECIMAL (4, 2)  NULL,
    [DomesticCom]               DECIMAL (4, 2)  NULL,
    [IntlCom]                   DECIMAL (4, 2)  NULL,
    [DACom]                     DECIMAL (4, 2)  NULL,
    [PrecallCom]                DECIMAL (4, 2)  NULL,
    [Legacy22Com]               DECIMAL (4, 2)  NULL,
    [Legacy866Com]              DECIMAL (4, 2)  NULL,
    [LegacySave]                DECIMAL (4, 2)  NULL,
    [LastUpdate]                SMALLDATETIME   NULL,
    [RecordId]                  BIGINT          NOT NULL,
    [UserName]                  VARCHAR (20)    NULL
);

