CREATE TABLE [dbo].[tblAgent] (
    [AgentID]       INT           NOT NULL,
    [Company]       VARCHAR (50)  NOT NULL,
    [FirstName]     VARCHAR (30)  NULL,
    [LastName]      VARCHAR (30)  NULL,
    [Address1]      VARCHAR (50)  NULL,
    [Address2]      VARCHAR (30)  NULL,
    [City]          VARCHAR (30)  NULL,
    [StateCode]     VARCHAR (2)   NULL,
    [Zip]           VARCHAR (10)  NULL,
    [Phone]         VARCHAR (20)  NULL,
    [PhoneExt]      VARCHAR (5)   NULL,
    [Fax]           VARCHAR (20)  NULL,
    [FaxExt]        VARCHAR (5)   NULL,
    [CellPhone]     VARCHAR (20)  NULL,
    [Title]         VARCHAR (50)  NULL,
    [INCommRate]    FLOAT (53)    NULL,
    [CACommRate]    FLOAT (53)    NULL,
    [DACommRate]    FLOAT (53)    NULL,
    [CCCommRate]    FLOAT (53)    NULL,
    [SVCommRate]    FLOAT (53)    NULL,
    [CLCommRate]    FLOAT (53)    NULL,
    [IN22CommRate]  FLOAT (53)    NULL,
    [CA22CommRate]  FLOAT (53)    NULL,
    [DBCommRate]    FLOAT (53)    NULL,
    [MMCommRate]    FLOAT (53)    NULL,
    [COCommRate]    FLOAT (53)    NULL,
    [StatementType] VARCHAR (10)  NULL,
    [AgentType]     CHAR (10)     NULL,
    [LibraryCode]   VARCHAR (2)   NULL,
    [EmailAddress]  VARCHAR (60)  NULL,
    [MainAgentID]   INT           NULL,
    [entitycode]    CHAR (3)      NULL,
    [IconURL]       VARCHAR (100) NULL,
    CONSTRAINT [PK_tblAgent] PRIMARY KEY CLUSTERED ([AgentID] ASC)
);

