CREATE TABLE [dbo].[tblCDRTemp] (
    [FacilityName]  VARCHAR (70)   NULL,
    [S1]            CHAR (1)       DEFAULT ('|') NULL,
    [FacilityID]    INT            NULL,
    [S2]            CHAR (1)       DEFAULT ('|') NULL,
    [FromNo]        VARCHAR (10)   NULL,
    [S3]            CHAR (1)       DEFAULT ('|') NULL,
    [toNo]          VARCHAR (16)   NULL,
    [S4]            CHAR (1)       DEFAULT ('|') NULL,
    [RecordID]      BIGINT         NULL,
    [S5]            CHAR (1)       DEFAULT ('|') NULL,
    [FromCity]      VARCHAR (20)   NULL,
    [S6]            CHAR (1)       DEFAULT ('|') NULL,
    [FromState]     VARCHAR (2)    NULL,
    [S7]            CHAR (1)       DEFAULT ('|') NULL,
    [ToCity]        VARCHAR (20)   NULL,
    [S8]            CHAR (1)       DEFAULT ('|') NULL,
    [ToState]       VARCHAR (2)    NULL,
    [S9]            CHAR (1)       DEFAULT ('|') NULL,
    [StationID]     VARCHAR (20)   NULL,
    [S10]           CHAR (1)       DEFAULT ('|') NULL,
    [LocationName]  VARCHAR (25)   NULL,
    [S11]           CHAR (1)       DEFAULT ('|') NULL,
    [InmateID]      VARCHAR (12)   NULL,
    [S12]           CHAR (1)       DEFAULT ('|') NULL,
    [PIN]           VARCHAR (12)   NULL,
    [S13]           CHAR (1)       DEFAULT ('|') NULL,
    [CallingCard]   VARCHAR (12)   NULL,
    [S14]           CHAR (1)       DEFAULT ('|') NULL,
    [RevenuePeriod] VARCHAR (4)    NULL,
    [S15]           CHAR (1)       DEFAULT ('|') NULL,
    [CallStart]     DATETIME       NULL,
    [S16]           CHAR (1)       DEFAULT ('|') NULL,
    [CallEnd]       DATETIME       NULL,
    [S17]           CHAR (1)       DEFAULT ('|') NULL,
    [Duration]      INT            NULL,
    [S18]           CHAR (1)       DEFAULT ('|') NULL,
    [BillType]      VARCHAR (25)   NULL,
    [S19]           CHAR (1)       DEFAULT ('|') NULL,
    [CallType]      VARCHAR (25)   NULL,
    [S20]           CHAR (1)       DEFAULT ('|') NULL,
    [CallRevenue]   NUMERIC (5, 2) NULL,
    [S21]           CHAR (1)       DEFAULT ('|') NULL,
    [Tax]           NUMERIC (5, 2) NULL,
    [S22]           CHAR (1)       DEFAULT ('|') NULL,
    [Validation]    VARCHAR (20)   NULL,
    [S23]           CHAR (1)       DEFAULT ('|') NULL,
    [ErrorCode]     VARCHAR (25)   NULL,
    [S24]           CHAR (1)       DEFAULT ('|') NULL,
    [LIDBcode]      VARCHAR (10)   NULL,
    [S25]           CHAR (1)       DEFAULT ('|') NULL,
    [Complete]      CHAR (1)       NULL
);

