CREATE TABLE [dbo].[tblFacilityOption_backUp] (
    [FacilityID]          INT          NOT NULL,
    [AccuPIN]             BIT          NULL,
    [BioMetric]           BIT          NULL,
    [AudioMining]         BIT          NULL,
    [FTPfolderName]       VARCHAR (25) NULL,
    [SecretPin]           BIT          NULL,
    [inmateStatus]        TINYINT      NULL,
    [AutoPin]             TINYINT      NULL,
    [NameRecord]          BIT          NULL,
    [VisitRegReq]         BIT          NULL,
    [VisitApmApprovedReq] BIT          NULL,
    [Languages]           VARCHAR (60) NULL,
    [FormsOpt]            BIT          NULL,
    [SoftphoneOpt]        BIT          NULL,
    [VoiceMessageOpt]     TINYINT      NULL,
    [EmailOpt]            BIT          NULL,
    [InfoSysOpt]          BIT          NULL,
    [AutoPAN]             TINYINT      NULL,
    [ModifyDate]          DATETIME     NULL,
    [VideoMessageOpt]     BIT          NULL,
    [PictureOpt]          BIT          NULL,
    [LawLibOpt]           BIT          NULL,
    [VideoVisitOpt]       BIT          NULL,
    [CommissaryOpt]       BIT          NULL,
    [AVSopt]              BIT          NULL,
    [MediaOpt]            BIT          NULL,
    [HandbookOpt]         BIT          NULL
);

