CREATE TABLE [dbo].[tblFacilityOption] (
    [FacilityID]          INT           NOT NULL,
    [AccuPIN]             BIT           NULL,
    [BioMetric]           BIT           NULL,
    [AudioMining]         BIT           CONSTRAINT [DF_tblFacilityOption_AudioMining] DEFAULT ((1)) NULL,
    [FTPfolderName]       VARCHAR (25)  NULL,
    [SecretPin]           BIT           NULL,
    [inmateStatus]        TINYINT       NULL,
    [AutoPin]             TINYINT       NULL,
    [NameRecord]          BIT           NULL,
    [VisitRegReq]         BIT           NULL,
    [VisitApmApprovedReq] BIT           DEFAULT ((1)) NULL,
    [Languages]           VARCHAR (300) NULL,
    [FormsOpt]            BIT           NULL,
    [SoftphoneOpt]        BIT           NULL,
    [VoiceMessageOpt]     TINYINT       DEFAULT ((0)) NULL,
    [EmailOpt]            BIT           DEFAULT ((0)) NULL,
    [InfoSysOpt]          BIT           DEFAULT ((0)) NULL,
    [AutoPAN]             TINYINT       NULL,
    [ModifyDate]          DATETIME      DEFAULT (getdate()) NULL,
    [VideoMessageOpt]     BIT           NULL,
    [PictureOpt]          BIT           NULL,
    [LawLibOpt]           BIT           NULL,
    [VideoVisitOpt]       BIT           NULL,
    [CommissaryOpt]       BIT           DEFAULT ((0)) NULL,
    [AVSopt]              BIT           NULL,
    [MediaOpt]            BIT           NULL,
    [HandbookOpt]         BIT           NULL,
    [PinChangeOpt]        BIT           NULL,
    [MobileFlatForm]      TINYINT       NULL,
    [InmatePINOpt]        BIT           NULL,
    [DebitCardLessOpt]    TINYINT       NULL,
    [Record2SideOpt]      BIT           DEFAULT ((0)) NULL,
    [AssignLocationOpt]   BIT           NULL,
    [DNIrestrictOpt]      BIT           NULL,
    CONSTRAINT [PK_tblFacilityOption] PRIMARY KEY CLUSTERED ([FacilityID] ASC),
    CONSTRAINT [FK_tblFacilityOption_tblFacility] FOREIGN KEY ([FacilityID]) REFERENCES [dbo].[tblFacility] ([FacilityID])
);

