CREATE TABLE [dbo].[tblGrievanceForm_BackUp] (
    [FormID]                         INT            NOT NULL,
    [FacilityID]                     INT            NOT NULL,
    [InmateID]                       VARCHAR (12)   NOT NULL,
    [BookSO]                         VARCHAR (12)   NOT NULL,
    [InmateLocation]                 TINYINT        NOT NULL,
    [HousingUnit]                    VARCHAR (25)   NOT NULL,
    [Grievance]                      VARCHAR (2000) NULL,
    [GrievanceReportTime]            DATETIME       NOT NULL,
    [GrievanceSignature]             VARCHAR (50)   NOT NULL,
    [ReceivingOfficerName]           VARCHAR (50)   NULL,
    [ReceivedTime]                   DATETIME       NULL,
    [ReceivingOfficerSignature]      VARCHAR (50)   NULL,
    [OfficerResponse]                VARCHAR (2000) NULL,
    [OfficerName]                    VARCHAR (50)   NULL,
    [OfficerSignature]               VARCHAR (50)   NULL,
    [AcceptOfficerSignature]         VARCHAR (50)   NULL,
    [AcceptOfficerTime]              DATETIME       NULL,
    [OfficerResponseTime]            DATETIME       NULL,
    [AppealOfficerResponseTime]      DATETIME       NULL,
    [ApealOfficerSignature]          VARCHAR (50)   NULL,
    [SupervisorReview]               VARCHAR (2000) NULL,
    [SupervisorName]                 VARCHAR (50)   NULL,
    [SupervisorSignature]            VARCHAR (50)   NULL,
    [RequestReviewBy]                TINYINT        NULL,
    [AcceptSupervisorResolutionTime] DATETIME       NULL,
    [AcceptSupervisorSignature]      VARCHAR (50)   NULL,
    [SupervisorResponseTime]         DATETIME       NULL,
    [AppealSupervisorSignature]      VARCHAR (50)   NULL,
    [AppealSupervisorTime]           DATETIME       NULL,
    [CommanderResponse]              VARCHAR (2000) NULL,
    [CommanderName]                  VARCHAR (50)   NULL,
    [CommanderSignature]             VARCHAR (50)   NULL,
    [CommanderResponseTime]          DATETIME       NULL,
    [AcceptCommanderTime]            DATETIME       NULL,
    [AcceptCommanderSignature]       VARCHAR (50)   NULL,
    [AppealCommanderSignature]       VARCHAR (50)   NULL,
    [AppealCommanderTime]            DATETIME       NULL,
    [SheriffResponse]                VARCHAR (2000) NULL,
    [SheriffName]                    VARCHAR (50)   NULL,
    [SheriffResponseTime]            DATETIME       NULL,
    [SheriffSignature]               VARCHAR (50)   NULL,
    [FinalSignature]                 VARCHAR (50)   NULL,
    [FinalSignatureTime]             DATETIME       NULL,
    [Status]                         TINYINT        NULL,
    [GrievancetypeID]                TINYINT        NULL,
    [RoomBedNo]                      VARCHAR (8)    NULL,
    [GvIssue]                        VARCHAR (800)  NULL,
    [ActionRequest]                  VARCHAR (800)  NULL,
    [FirstLevelDueDate]              DATETIME       NULL,
    [SecondLevelDueDate]             DATETIME       NULL,
    [FirstLevelInterviewDate]        DATETIME       NULL,
    [SecondLevelInterviewDate]       DATETIME       NULL,
    [Category]                       NCHAR (50)     NULL,
    [FirstInterviewDate]             DATETIME       NULL,
    [FirstInterviewLocation]         NCHAR (50)     NULL,
    [SecondInterviewDate]            DATETIME       NULL,
    [SecondInterviewLocation]        NCHAR (50)     NULL,
    [SecondAppeal]                   VARCHAR (1000) NULL,
    [ThirdAppeal]                    VARCHAR (1000) NULL,
    [InmateLastStatement]            VARCHAR (500)  NULL,
    [OfficerLastStatement]           VARCHAR (500)  NULL,
    [LogNo]                          VARCHAR (25)   NULL,
    [ComplaintCheckBox]              BIT            NULL,
    [GrievanceCheckBox]              BIT            NULL,
    [otherForm]                      VARCHAR (100)  NULL,
    [DeviceName]                     VARCHAR (20)   NULL,
    [AcceptSheriffSignature]         VARCHAR (50)   NULL,
    [AcceptSheriffTime]              DATETIME       NULL,
    [AppealSheriffSignature]         VARCHAR (50)   NULL,
    [AppealSheriffTime]              DATETIME       NULL,
    [MajorResponse]                  VARCHAR (500)  NULL,
    [MajorResponseTime]              DATETIME       NULL,
    [MajorSignature]                 VARCHAR (50)   NULL,
    [ApprovedSection2Signature]      VARCHAR (50)   NULL,
    [ApprovedSection2Time]           VARCHAR (50)   NULL,
    [ApprovedSection3Signature]      VARCHAR (50)   NULL,
    [ApprovedSection3Time]           VARCHAR (50)   NULL,
    CONSTRAINT [PK_tblGrievanceForm] PRIMARY KEY CLUSTERED ([FormID] ASC)
);

