CREATE TABLE [dbo].[tblInmateArchive] (
    [InmateID]          VARCHAR (12)  NOT NULL,
    [CaseID]            INT           NULL,
    [LastName]          VARCHAR (25)  NULL,
    [FirstName]         VARCHAR (25)  NULL,
    [MidName]           VARCHAR (25)  NULL,
    [Status]            TINYINT       NULL,
    [DNIRestrict]       BIT           CONSTRAINT [DF_tblInmateArchive_DNIRestrict] DEFAULT ((0)) NULL,
    [DateTimeRestrict]  BIT           CONSTRAINT [DF_tblInmateArchive_DateTimeRestrict] DEFAULT ((0)) NULL,
    [AccessType]        TINYINT       NULL,
    [AlertEmail]        VARCHAR (100) NULL,
    [AlertPage]         CHAR (10)     NULL,
    [AlertPhone]        CHAR (10)     NULL,
    [AlertCellPhones]   VARCHAR (100) NULL,
    [DNILimit]          TINYINT       CONSTRAINT [DF_tblInmateArchive_DNILimit] DEFAULT ((20)) NULL,
    [FacilityId]        INT           NOT NULL,
    [inputdate]         SMALLDATETIME CONSTRAINT [DF_tblInmateArchive_inputdate] DEFAULT (getdate()) NULL,
    [UserName]          VARCHAR (20)  NULL,
    [ModifyDate]        SMALLDATETIME NULL,
    [PIN]               VARCHAR (12)  NOT NULL,
    [MaxCallTime]       SMALLINT      CONSTRAINT [DF_tblInmateArchive_MaxCallTime] DEFAULT ((15)) NULL,
    [HourlyFreq]        TINYINT       CONSTRAINT [DF_tblInmateArchive_HourlyFreq] DEFAULT ((1)) NULL,
    [DailyFreq]         TINYINT       CONSTRAINT [DF_tblInmateArchive_DailyFreq] DEFAULT ((1)) NULL,
    [WeeklyFreq]        TINYINT       CONSTRAINT [DF_tblInmateArchive_WeeklyFreq] DEFAULT ((1)) NULL,
    [MonthlyFreq]       TINYINT       CONSTRAINT [DF_tblInmateArchive_MonthlyFreq] DEFAULT ((1)) NULL,
    [MaxCallPerHour]    SMALLINT      CONSTRAINT [DF__tblInmateArchive__MaxCa__24F264BB] DEFAULT ((0)) NULL,
    [MaxCallPerDay]     SMALLINT      CONSTRAINT [DF__tblInmateArchive__MaxCa__25E688F4] DEFAULT ((0)) NULL,
    [MaxCallPerWeek]    SMALLINT      CONSTRAINT [DF__tblInmateArchive__MaxCa__26DAAD2D] DEFAULT ((0)) NULL,
    [MaxCallPerMonth]   SMALLINT      CONSTRAINT [DF__tblInmateArchive__MaxCa__27CED166] DEFAULT ((0)) NULL,
    [DOB]               VARCHAR (12)  NULL,
    [SEX]               CHAR (1)      NULL,
    [TTY]               BIT           CONSTRAINT [DF__tblInmateArchive__TTY__6B4FD30B] DEFAULT ((0)) NULL,
    [StartDate]         DATETIME      NULL,
    [EndDate]           DATETIME      NULL,
    [DebitCardOpt]      BIT           NULL,
    [NameRecorded]      BIT           NULL,
    [AssignToDivision]  INT           NULL,
    [AssignToLocation]  INT           NULL,
    [AssignToStation]   INT           NULL,
    [BlockPeriodOfTime] BIT           NULL,
    [PANNotAllow]       BIT           NULL,
    [NotAllowLimit]     TINYINT       NULL,
    [BioRegister]       BIT           DEFAULT ((0)) NULL,
    [ReBook]            TINYINT       DEFAULT ((0)) NULL,
    [RebookDate]        DATETIME      NULL,
    [CustodialOpt]      BIT           DEFAULT ((0)) NULL,
    [VisitSusStartDate] DATE          NULL,
    [VisitSusEndDate]   DATE          NULL,
    [VisitApprovedReq]  BIT           NULL,
    [AdminNote]         VARCHAR (150) NULL,
    [RaceID]            TINYINT       NULL,
    [InmateNote]        VARCHAR (200) NULL,
    [ActiveDate]        DATETIME      NULL,
    [FreeCallRemain]    TINYINT       DEFAULT ((0)) NULL,
    [PrimaryLanguage]   TINYINT       DEFAULT ((0)) NULL,
    CONSTRAINT [PK_tblInmateArchive] PRIMARY KEY CLUSTERED ([InmateID] ASC, [FacilityId] ASC, [PIN] ASC)
);

