CREATE TABLE [dbo].[tblMedicalKiteForm] (
    [FormID]            INT            NOT NULL,
    [FacilityID]        INT            NOT NULL,
    [InmateID]          VARCHAR (12)   NULL,
    [BookingNo]         VARCHAR (12)   NULL,
    [AliasName]         VARCHAR (40)   NULL,
    [DOB]               VARCHAR (10)   NULL,
    [RequestDate]       DATETIME       NULL,
    [InmateLocation]    VARCHAR (30)   NULL,
    [Dental]            BIT            NULL,
    [HIV]               BIT            NULL,
    [Medical]           BIT            NULL,
    [Psychiatric]       BIT            NULL,
    [DescriptOfProblem] VARCHAR (2000) NULL,
    [LengthOfProblem]   VARCHAR (40)   NULL,
    [InmateSignature]   VARCHAR (50)   NOT NULL,
    [Response]          VARCHAR (2000) NULL,
    [ReviewedBy]        VARCHAR (30)   NULL,
    [ReviewedDate]      DATETIME       NULL,
    [StaffNote]         VARCHAR (300)  NULL,
    [NoteBy]            VARCHAR (30)   NULL,
    [NoteDate]          DATETIME       NULL,
    [Status]            TINYINT        NULL,
    [MDClinic]          BIT            NULL,
    [Nurse]             BIT            NULL,
    [ChartReview]       BIT            NULL,
    [MentalHealth]      BIT            NULL,
    [RoomBedNo]         VARCHAR (10)   NULL,
    [ReleaseDate]       VARCHAR (10)   NULL,
    [Copay]             BIT            DEFAULT ((0)) NULL,
    [VisitedClinic]     BIT            DEFAULT ((0)) NULL,
    [ProviderName]      VARCHAR (40)   NULL,
    CONSTRAINT [PK_tblMedicalKiteForm] PRIMARY KEY CLUSTERED ([FormID] ASC)
);

