CREATE TABLE [dbo].[tblPrepaidService] (
    [PhoneNo]        CHAR (10)      NOT NULL,
    [PaymentTypeID]  TINYINT        CONSTRAINT [DF_tblPrepaid_PaymentTypeIDservice] DEFAULT (0) NULL,
    [RelationshipID] TINYINT        CONSTRAINT [DF_tblPrepaid_RelationshipIDService] DEFAULT (4) NULL,
    [FirstName]      VARCHAR (25)   NULL,
    [LastName]       VARCHAR (25)   NULL,
    [MI]             CHAR (1)       NULL,
    [Address]        VARCHAR (75)   NULL,
    [City]           VARCHAR (20)   NULL,
    [State]          CHAR (2)       NULL,
    [ZipCode]        VARCHAR (10)   NULL,
    [Country]        VARCHAR (20)   CONSTRAINT [DF_tblPrepaid_CountryService] DEFAULT ('USA') NULL,
    [Email]          VARCHAR (40)   NULL,
    [Balance]        NUMERIC (7, 2) NULL,
    [status]         TINYINT        NULL,
    [inputDate]      SMALLDATETIME  CONSTRAINT [DF_tblPrepaid_inputDateService] DEFAULT (getdate()) NULL,
    [ModifyDate]     SMALLDATETIME  NULL,
    [UserName]       VARCHAR (20)   NULL,
    [FacilityID]     INT            NOT NULL,
    [InmateID]       INT            NULL,
    [note]           VARCHAR (50)   NULL,
    [InmateName]     VARCHAR (50)   NULL,
    [EndUserID]      INT            NULL,
    [CountryCode]    VARCHAR (3)    CONSTRAINT [DF_tblPrepaid_CountryCodeService] DEFAULT ('1') NULL,
    CONSTRAINT [PK_tblPrepaidservice] PRIMARY KEY CLUSTERED ([PhoneNo] ASC, [FacilityID] ASC),
    CONSTRAINT [FK_tblPrepaid_tblpaymentTypeService] FOREIGN KEY ([PaymentTypeID]) REFERENCES [dbo].[tblpaymentType] ([paymentTypeID]),
    CONSTRAINT [FK_tblPrepaid_tblRelationShipService] FOREIGN KEY ([RelationshipID]) REFERENCES [dbo].[tblRelationShip] ([RelationshipID])
);

