CREATE TABLE [dbo].[tblVisitors] (
    [VLastName]         VARCHAR (25)  NULL,
    [VFirstName]        VARCHAR (25)  NULL,
    [VMi]               CHAR (1)      NULL,
    [Address]           VARCHAR (100) NULL,
    [City]              VARCHAR (25)  NULL,
    [State]             VARCHAR (2)   NULL,
    [Zipcode]           VARCHAR (9)   NULL,
    [Phone1]            VARCHAR (10)  NULL,
    [Phone2]            VARCHAR (10)  NULL,
    [Email]             VARCHAR (35)  NULL,
    [InmateID]          VARCHAR (12)  NOT NULL,
    [FacilityID]        INT           NOT NULL,
    [RelationshipID]    TINYINT       NULL,
    [RecordOpt]         CHAR (1)      CONSTRAINT [DF__tblVisito__Recor__0F582957] DEFAULT ('Y') NULL,
    [InputDate]         DATETIME      NULL,
    [ModifyDate]        DATETIME      NULL,
    [UserName]          VARCHAR (25)  NULL,
    [Approved]          CHAR (1)      CONSTRAINT [DF_tblVisitors_Approved] DEFAULT ('Y') NULL,
    [DriverLicense]     VARCHAR (25)  CONSTRAINT [DF__tblVisito__Drive__114071C9] DEFAULT ('') NULL,
    [EndUserID]         VARCHAR (12)  NULL,
    [VNote]             VARCHAR (150) NULL,
    [VImage]            VARCHAR (150) NULL,
    [AlertEmail]        VARCHAR (50)  NULL,
    [AlertText]         VARCHAR (20)  NULL,
    [RelationShip]      VARCHAR (20)  NULL,
    [VisitorID]         INT           NOT NULL,
    [StateID]           SMALLINT      NULL,
    [CountryID]         SMALLINT      NULL,
    [VisitorMembers]    TINYINT       CONSTRAINT [DF_tblVisitors_VisitorMembers] DEFAULT ((1)) NULL,
    [EntityID]          VARCHAR (20)  NULL,
    [DOB]               VARCHAR (12)  NULL,
    [Gender]            VARCHAR (1)   NULL,
    [StateBarLicense]   VARCHAR (20)  NULL,
    [VDLImage]          VARCHAR (150) NULL,
    [ApprovedBy]        VARCHAR (25)  NULL,
    [ApprovedApm]       BIT           NULL,
    [ApprovedDate]      DATETIME      NULL,
    [PerDay]            TINYINT       NULL,
    [PerDayPerInmate]   TINYINT       NULL,
    [PerWeek]           TINYINT       NULL,
    [PerWeekPerInmate]  TINYINT       NULL,
    [PerMonth]          TINYINT       NULL,
    [PerMonthPerInmate] TINYINT       NULL,
    CONSTRAINT [PK_tblVisitors] PRIMARY KEY CLUSTERED ([VisitorID] ASC),
    CONSTRAINT [FK_tblVisitors_tblfacility] FOREIGN KEY ([FacilityID]) REFERENCES [dbo].[tblFacility] ([FacilityID]),
    CONSTRAINT [FK_tblVisitors_tblStates] FOREIGN KEY ([StateID]) REFERENCES [dbo].[tblStates] ([StateID]),
    CONSTRAINT [FK_tblVisitors_tblVisitors_status] FOREIGN KEY ([Approved]) REFERENCES [dbo].[tblVisitorStatus] ([Status])
);


GO
CREATE NONCLUSTERED INDEX [ind_entity]
    ON [dbo].[tblVisitors]([EntityID] ASC);

