CREATE TABLE [dbo].[tblVisitors_backUp2] (
    [VLastName]       VARCHAR (25)  NULL,
    [VFirstName]      VARCHAR (25)  NULL,
    [VMi]             CHAR (1)      NULL,
    [Address]         VARCHAR (100) NULL,
    [City]            VARCHAR (25)  NULL,
    [State]           VARCHAR (2)   NULL,
    [Zipcode]         VARCHAR (9)   NULL,
    [Phone1]          VARCHAR (10)  NULL,
    [Phone2]          VARCHAR (10)  NULL,
    [Email]           VARCHAR (35)  NULL,
    [InmateID]        VARCHAR (12)  NOT NULL,
    [FacilityID]      INT           NOT NULL,
    [RelationshipID]  TINYINT       NULL,
    [RecordOpt]       CHAR (1)      NULL,
    [InputDate]       DATETIME      NULL,
    [ModifyDate]      DATETIME      NULL,
    [UserName]        VARCHAR (25)  NULL,
    [Approved]        CHAR (1)      NULL,
    [DriverLicense]   VARCHAR (25)  NULL,
    [EndUserID]       VARCHAR (12)  NULL,
    [VNote]           VARCHAR (150) NULL,
    [VImage]          VARCHAR (150) NULL,
    [AlertEmail]      VARCHAR (50)  NULL,
    [AlertText]       VARCHAR (20)  NULL,
    [RelationShip]    VARCHAR (20)  NULL,
    [VisitorID]       INT           NOT NULL,
    [StateID]         SMALLINT      NULL,
    [CountryID]       SMALLINT      NULL,
    [VisitorMembers]  TINYINT       NULL,
    [EntityID]        VARCHAR (20)  NULL,
    [DOB]             VARCHAR (12)  NULL,
    [Gender]          VARCHAR (1)   NULL,
    [StateBarLicense] VARCHAR (20)  NULL,
    [VDLImage]        VARCHAR (150) NULL,
    [ApprovedBy]      VARCHAR (25)  NULL,
    [ApprovedApm]     BIT           NULL,
    [ApprovedDate]    DATETIME      NULL
);

