CREATE TABLE [dbo].[tblVisitEnduserSchedule_backUp] (
    [ApmNo]            VARCHAR (15)   NOT NULL,
    [FacilityID]       INT            NOT NULL,
    [InmateID]         VARCHAR (12)   NULL,
    [InmateName]       VARCHAR (50)   NULL,
    [EndUserID]        VARCHAR (12)   NULL,
    [RequestedTime]    DATETIME       NULL,
    [RequestBy]        TINYINT        NULL,
    [ApprovedTime]     DATETIME       NULL,
    [ApprovedBy]       VARCHAR (25)   NULL,
    [ApmDate]          SMALLDATETIME  NOT NULL,
    [ApmTime]          TIME (0)       NOT NULL,
    [status]           TINYINT        NOT NULL,
    [CreatedBy]        VARCHAR (25)   NULL,
    [visitType]        TINYINT        NULL,
    [LimitTime]        INT            NULL,
    [VisitorID]        INT            NOT NULL,
    [StationID]        VARCHAR (25)   NULL,
    [InmateLogInID]    VARCHAR (25)   NULL,
    [VisitorLogInID]   VARCHAR (25)   NULL,
    [Note]             VARCHAR (100)  NULL,
    [AlertCellPhone]   VARCHAR (10)   NULL,
    [AlertCellCarrier] VARCHAR (25)   NULL,
    [VisitDuration]    SMALLINT       NULL,
    [locationID]       INT            NULL,
    [TotalCharge]      NUMERIC (5, 2) NULL,
    [RecordStatus]     TINYINT        NULL,
    [ChatServerIP]     VARCHAR (20)   NULL,
    [RecordOpt]        CHAR (1)       NULL,
    [Relationship]     VARCHAR (30)   NULL,
    [RoomID]           INT            NOT NULL,
    [CancelBy]         VARCHAR (25)   NULL,
    [SendJMS]          TINYINT        NULL,
    [CancelDate]       DATETIME       NULL
);

