CREATE TABLE [dbo].[tblVisitFacilityConfig] (
    [FacilityID]                    INT          NOT NULL,
    [VisitOpt]                      TINYINT      NULL,
    [VisitRegReq]                   BIT          NULL,
    [VisitApmApprovedReq]           BIT          NULL,
    [VisitIDReq]                    BIT          NULL,
    [VisitPicReq]                   BIT          NULL,
    [ContactPhone]                  NCHAR (10)   NULL,
    [ContactCellPhone]              NCHAR (10)   NULL,
    [ContactEmail]                  VARCHAR (50) NULL,
    [InterSection]                  TINYINT      NOT NULL,
    [HourBeforeVisit]               TINYINT      NOT NULL,
    [HourBeforeCancel]              TINYINT      NOT NULL,
    [MaxDuration]                   TINYINT      NOT NULL,
    [MinDuration]                   TINYINT      NOT NULL,
    [Increment]                     TINYINT      NOT NULL,
    [MaxVisitMember]                TINYINT      CONSTRAINT [DF__tblVisitF__MaxVi__33EA8F88] DEFAULT ((0)) NULL,
    [VisitPerDay]                   TINYINT      NULL,
    [VisitPerWeek]                  TINYINT      NULL,
    [VisitPerMonth]                 TINYINT      NULL,
    [HourBeforeVisitOnSite]         TINYINT      CONSTRAINT [DF__tblVisitF__HourB__0ED9066A] DEFAULT ((0)) NULL,
    [InputDate]                     DATETIME     NULL,
    [ModifyDate]                    DATETIME     NULL,
    [UserName]                      VARCHAR (25) NULL,
    [RuleName]                      VARCHAR (15) NULL,
    [InmateRulename]                VARCHAR (10) NULL,
    [HourAllowSchedule]             SMALLINT     NULL,
    [RecordOpt]                     VARCHAR (1)  DEFAULT ('Y') NULL,
    [ScheduleRequestOpt]            BIT          NULL,
    [ViewScheduleOpt]               BIT          NULL,
    [ContactEmail2]                 VARCHAR (50) NULL,
    [ContactEmail3]                 VARCHAR (50) NULL,
    [VisitorVisitPerDay]            TINYINT      NULL,
    [VisitorVisitPerWeek]           TINYINT      NULL,
    [VisitorVisitPerMonth]          TINYINT      NULL,
    [VisitorVisitPerDayPerInmate]   TINYINT      NULL,
    [VisitorVisitPerWeekPerInmate]  TINYINT      NULL,
    [VisitorVisitPerMonthPerInmate] TINYINT      NULL,
    CONSTRAINT [PK_tblVisitFacilityConfig] PRIMARY KEY CLUSTERED ([FacilityID] ASC),
    CONSTRAINT [FK_tblVisitFacilityConfig_tblFacility] FOREIGN KEY ([FacilityID]) REFERENCES [dbo].[tblFacility] ([FacilityID]),
    CONSTRAINT [FK_tblVisitFacilityConfig_tblVisitOpt] FOREIGN KEY ([VisitOpt]) REFERENCES [dbo].[tblVisitOption] ([VisitOptID])
);

