CREATE TABLE [dbo].[Tel_Info] (
    [TELNUM]  NVARCHAR (6)  NOT NULL,
    [STATUS]  NVARCHAR (1)  NULL,
    [EFFDATE] SMALLDATETIME NULL,
    [ILEC]    TINYINT       NULL,
    [PREMIUM] TINYINT       NULL,
    [COTYPE]  NVARCHAR (1)  NULL,
    [CLUST]   NVARCHAR (10) NULL,
    [TELCO]   NVARCHAR (4)  NULL,
    [CITY]    NVARCHAR (30) NULL,
    [RCNAME]  NVARCHAR (10) NULL,
    [ST]      NVARCHAR (2)  NULL,
    [RCV]     SMALLINT      NULL,
    [RCH]     SMALLINT      NULL,
    [LATA]    NVARCHAR (5)  NULL,
    [CP_BUS]  NVARCHAR (2)  NULL,
    [CP_RES]  NVARCHAR (2)  NULL,
    [CP_IBUS] NVARCHAR (2)  NULL,
    [CP_IRES] NVARCHAR (2)  NULL,
    CONSTRAINT [PK_Tel_Info] PRIMARY KEY CLUSTERED ([TELNUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ind_clust]
    ON [dbo].[Tel_Info]([CLUST] ASC);

