CREATE TABLE [dbo].[VHSTATES] (
    [ST]        NVARCHAR (2)  NULL,
    [STATENAME] NVARCHAR (20) NULL,
    [NPACODE]   NVARCHAR (1)  NULL,
    [RBOC]      NVARCHAR (4)  NULL,
    [BOC]       NVARCHAR (4)  NULL
);

