CREATE TABLE [dbo].[VHTELCO] (
    [TYPE]    NVARCHAR (4)  NULL,
    [TELCOID] NVARCHAR (4)  NOT NULL,
    [NAME]    NVARCHAR (80) NULL,
    [TELCO]   NVARCHAR (4)  NULL,
    [ST]      NVARCHAR (2)  NOT NULL,
    [RBOC]    NVARCHAR (2)  NULL,
    [ORIG]    NVARCHAR (5)  NULL,
    [ORIG5]   NVARCHAR (5)  NULL,
    [ORIG6]   NVARCHAR (5)  NULL,
    [ORIGSA]  NVARCHAR (5)  NULL,
    [ORIGSA0] NVARCHAR (5)  NULL,
    [ORIGLCA] NVARCHAR (5)  NULL,
    [ILEC]    TINYINT       NULL
);

