
CREATE PROCEDURE [dbo].[p_get_billedCall_fromLA_per_date]

AS
declare  @connectDate char(6)

SET  @connectDate = convert(char(6),dateadd(day,-1,getdate()),12) 
Select  top 100  RecordID,
	 Calldate,
 	ConnectTime,
 	FromNo ,
 	ToNo ,  
	BillToNo ,  
	MethodOfRecord, 
	billType,
	 CallType,
 	FromState, 
	FromCity ,
  	ToState, 
	ToCity  ,   
	isnull(CreditCardType,'') CreditCardType, 
	isnull(CreditCardNo,'') CreditCardNo  , 
	 isnull(CreditCardExp,'') CreditCardExp,
	isnull( CreditCardZip,'') CreditCardZip,
	isnull(CreditCardCVV,'')CreditCardCVV, 
	CallPeriod ,
	LibraryCode, 
	Isnull(Indicator19,'') Indicator19,
	isnull( SettlementCode,'8')  SettlementCode,
	isnull(projectCode,'') projectCode, 
	isnull(complete,'1') complete ,
	isnull(errorCode ,'0') errorCode ,
	ratePlanID,
 	firstMinute,
  	nextMinute, 
  	connectFee ,
 	 isnull(minDuration,1) minDuration , 
	isnull(RateClass,'') RateClass, 
 	userName , 
 	RecordDate      ,
	totalSurcharge,
 	duration  , 
	 isnull( Dberror,'N') Dberror,
 	isnull(ResponseCode,'') ResponseCode,  
	 isnull( Pif,0)  Pif,   
 	isnull(NSF,0) NSF,  
	 isnull(  PSC,0) PSC ,  
 	isnull(AgentID,0) AgentID , 
   	RecordFile  ,  
   	isnull(    MinIncrement,1)  MinIncrement,
	FolderDate,
 	Channel, 
 	isnull(InmateID,'0') InmateID ,    
	CallRevenue, 
	PIN ,     
   	 FacilityID,
	 isnull( InRecordFile,'')    InRecordFile, 
   	isnull(  LocationId,0) LocationId, 
	 isnull(DivisionId ,0) DivisionId 
  from tblcallsbilled  with(nolock)  where  calldate = @connectDate

